# Generated by Django 2.2.24 on 2021-09-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('man', 'erkek'), ('women', 'kadin'), ('unisex', 'unisex')], default='unisex', max_length=10),
        ),
    ]
