# Generated by Django 2.2.24 on 2021-09-20 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_auto_20210919_0025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Corousel',
            new_name='Carousel',
        ),
    ]
