# Generated by Django 2.2.24 on 2021-10-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepet', '0002_shoppingcart_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
