# Generated by Django 2.2.24 on 2021-10-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepet', '0003_auto_20211010_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
