# Generated by Django 2.2.24 on 2021-10-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sepet', '0005_shoppingcart_fiyat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='fiyat',
        ),
    ]
