# Generated by Django 2.2.24 on 2021-10-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepet', '0006_remove_shoppingcart_fiyat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='sepet.ShopingCartItem'),
        ),
    ]
